### ISSUE TITLE
Upvote post API endpoint does not currently return anything

### ISSUE THREAD

**Issue by clyanide** [se701-group6/se701-assignment1#82]
Front end fetch() method requires that something is returned in the API endpoint call
## Expected Behavior

Upvote post route should return a value (e.g. success message)
## Current Behavior

Upvote post route does not return anything
## Possible Solution

Add return value for upvote route.
## Steps to Reproduce

1. Call fetch() on upvote post route

## Context (Environment)

Cannot call fetch() on upvote post API endpoint

## Detailed Description

Add a return message/value to upvote post endpoint
## Possible Implementation

Add a return message. e.g. successfully upvoted post

**Comment by ErnWong** [comment]
If we were not returning any response, then I think a 204 status should've been returned rather than a 200 status, and the frontend should not have asked for `application/json` in the accept header and should not have tried `responseBody.json()` . That might have been the reason why it wasn't working, but I haven't tested it - just my speculation. Returning something is not a bad idea though since we want an error message to be returned in some cases.

**Comment by ErnWong** [comment]
Reopening as the PR referenced does not fix this.

**Comment by ErnWong** [comment]
I approve

**Comment by timovv** [comment]
i 
approve

**Comment by WaiHaiDere** [comment]
i approve
